[features]
seeds = false
skip-lint = false
[programs.localnet]
bonk_paper_scissors = "bonk8yVf477u7s7nqttS6VXFTCjbV2S5MKxmojGAa4i"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kevinrodriguez/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
